# production environment specific only
# The production compose file will follow closely what was written in the Dockerrun.aws.json
version: "3.1"
services:
  client:
    image: "wakidur/multi-container-client"
    mem_limit: 128m
    hostname: client
  server:
    image: "wakidur/multi-container-server"
    mem_limit: 128m
    hostname: api
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PGUSER=$PGUSER
      - PGHOST=$PGHOST
      - PGDATABASE=$PGDATABASE
      - PGPASSWORD=$PGPASSWORD
      - PGPORT=$PGPORT
  worker:
    image: "wakidur/multi-container-worker"
    mem_limit: 128m
    hostname: worker
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
  nginx:
    image: "wakidur/multi-container-nginx"
    mem_limit: 128m
    hostname: nginx
    ports:
      - "80:80"