name: Deployment Docker Image CI
run-name: Deployment GitHub  Actions.

on:
  push:
    branches: ['main']

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Push Docker image to Docker Hub
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: client/
          push: true
          tags: wakidur/multi-client:latest
