name: Deployment Docker Image CI
run-name: Deployment GitHub  Actions.

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
  

    - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
    - run: docker build -t wakidur/react-test -f ./client/Dockerfile.dev ./client
    - run: docker run -e CI=true wakidur/react-test npm test

    - run: docker build -t wakidur/multi-client ./client
    - run: docker build -t wakidur/multi-nginx ./nginx
    - run: docker build -t wakidur/multi-server ./server
    - run: docker build -t wakidur/multi-worker ./worker

    - run: docker push wakidur/multi-client
    - run: docker push wakidur/multi-nginx
    - run: docker push wakidur/multi-server
    - run: docker push wakidur/multi-worker 
